### ISSUE TITLE
What is the license status of PargramMalagasy

### ISSUE THREAD

**Issue by SekouDiaoNlp** [llm2/PargramMalagasy#1]
Hi @llm2 ,

I am currently in the process of compiling a database of open source LFG grammars for as many languages as possible for [Ars Linguistica](https://github.com/Ars-Linguistica), a GitHub organization I recently founded to foster the efforts in buiding an open source LFG parser as well as a large collection of pen source LFG grammars. I found out your project and I would be delighted to add it to the database.

However, I can not find any licensing information for your grammar. Could you please confirm what’s the licensing status of your grammar?

I couldn’t find a way to contact you so I opened this issue.

Thank you very much.

By the way, if you want to join ARS Linguistica, you are lost welcome.

Cheers!

Sekou.

**Comment by llm2** [comment]
Hi Sekou,

the grammar is free to use. The license seems like a good addition so I merged your pull request.

**Comment by SekouDiaoNlp** [comment]
Thank you @llm2 .

Have a great day
